/**
 * Integration tests using real sample transaction data
 *
 * These tests exercise the full designation pipeline against actual
 * YNAB transaction data to ensure the system works end-to-end.
 */

import { readFileSync } from 'fs';
import { resolve, dirname } from 'path';
import { fileURLToPath } from 'url';

import {
  addHashtagsToTransactions,
  processTransactionsWithTrips,
  processTransactions,
  isTransferTransaction,
  computeSettlement,
  markSettled,
  settlementWatermark,
  summarizeGroups,
} from '../src/utils/designations/index.js';

import {
  extractAllHashtags,
  filterRelevantHashtags,
  extractTripHashtags,
} from '../src/utils/designations/extractors/hashtags.js';

import { getTripSummaries } from '../src/utils/designations/rules/tripRule.js';

import {
  groupByConsecutiveDates,
  getDateRange,
} from '../src/utils/designations/extractors/tripGrouper.js';

import { detect as detectTransfer } from '../src/utils/designations/rules/transferRule.js';
import { detect as detectHousehold } from '../src/utils/designations/rules/householdRule.js';

import { defaultConfig } from '../src/utils/designations/config.js';

// Mock localStorage (not available in Node)
const storage = {};
global.localStorage = {
  getItem: (key) => storage[key] ?? null,
  setItem: (key, value) => { storage[key] = value; },
  removeItem: (key) => { delete storage[key]; },
};

// Load fixture data
const __dirname = dirname(fileURLToPath(import.meta.url));
const sampleTransactions = JSON.parse(
  readFileSync(resolve(__dirname, 'fixtures/sample-transactions.json'), 'utf8')
);

describe('sample data integrity', () => {
  it('should load 161 transactions from two budgets', () => {
    expect(sampleTransactions.length).toBe(161);

    const sources = [...new Set(sampleTransactions.map(t => t.source))];
    expect(sources).toContain('left');
    expect(sources).toContain('right');
  });

  it('should have required raw fields on every transaction', () => {
    const requiredFields = ['id', 'date', 'amount', 'source'];

    for (const t of sampleTransactions) {
      for (const field of requiredFields) {
        expect(t).toHaveProperty(field);
      }
    }
  });

  it('should not have pre-computed designation fields', () => {
    const computedFields = [
      'autoTaggedAsBill', 'autoTaggedAsTransfer',
      'hashtags', 'relevantHashtags',
      'hasTripTag', 'hasHouseholdTag', 'hasTransferTag',
      'tripHashtags', 'tripName', 'isAutoGeneratedTrip',
    ];

    for (const t of sampleTransactions) {
      for (const field of computedFields) {
        expect(t).not.toHaveProperty(field);
      }
    }
  });
});

describe('hashtag extraction from real memos', () => {
  it('should extract #household tags from utility payment memos', () => {
    const hydro = sampleTransactions.find(t =>
      t.memo && t.memo.includes('#household')
    );
    expect(hydro).toBeDefined();

    const hashtags = extractAllHashtags(hydro);
    expect(hashtags).toContain('household');
  });

  it('should return empty for transactions without hashtags', () => {
    const noTags = sampleTransactions.find(t => t.memo && !t.memo.includes('#'));
    if (noTags) {
      expect(extractAllHashtags(noTags)).toEqual([]);
    }
  });

  it('should filter relevant hashtags correctly', () => {
    const allTags = sampleTransactions
      .flatMap(t => extractAllHashtags(t))
      .filter(Boolean);
    const relevant = filterRelevantHashtags(allTags);

    for (const tag of relevant) {
      const lower = tag.toLowerCase();
      expect(
        lower.startsWith('trip') || lower === 'household' || lower === 'transfer'
      ).toBe(true);
    }
  });
});

describe('transfer detection on real data', () => {
  it('should detect transfers between budgets with matching amounts', () => {
    const detectedTransfers = sampleTransactions.filter(t =>
      detectTransfer(t, sampleTransactions).matches
    );

    expect(detectedTransfers.length).toBeGreaterThan(0);

    // Transfers should always involve two different sources
    for (const t of detectedTransfers) {
      const result = detectTransfer(t, sampleTransactions);
      const match = result.matchingTransactions[0];
      expect(match.source).not.toBe(t.source);
      expect(Math.abs(match.amount)).toBe(Math.abs(t.amount));
    }
  });

  it('should not detect transfers between transactions from the same budget', () => {
    const leftOnly = sampleTransactions.filter(t => t.source === 'left');

    const falseTransfers = leftOnly.filter(t =>
      detectTransfer(t, leftOnly).matches
    );
    expect(falseTransfers).toHaveLength(0);
  });
});

describe('household detection on real data', () => {
  it('should detect household transactions by category patterns', () => {
    const detected = sampleTransactions.filter(t =>
      detectHousehold(t).matches
    );

    expect(detected.length).toBeGreaterThan(0);

    // All detected should match known household-like categories
    for (const t of detected) {
      const catLower = (t.category_name || '').toLowerCase();
      const groupLower = (t.category_group_name || '').toLowerCase();
      const patterns = [...defaultConfig.household.categoryPatterns, ...defaultConfig.household.categoryGroupPatterns];
      const matchesPattern = patterns.some(p =>
        catLower.includes(p.toLowerCase()) || groupLower.includes(p.toLowerCase())
      );
      expect(matchesPattern).toBe(true);
    }
  });
});

describe('addHashtagsToTransactions pipeline', () => {
  let processed;

  beforeAll(() => {
    processed = addHashtagsToTransactions(sampleTransactions);
  });

  it('should return the same number of transactions', () => {
    expect(processed.length).toBe(sampleTransactions.length);
  });

  it('should add hashtag arrays to every transaction', () => {
    for (const t of processed) {
      expect(t).toHaveProperty('hashtags');
      expect(t).toHaveProperty('relevantHashtags');
      expect(t).toHaveProperty('hasTripTag');
      expect(t).toHaveProperty('hasHouseholdTag');
      expect(t).toHaveProperty('hasTransferTag');
      expect(Array.isArray(t.hashtags)).toBe(true);
      expect(Array.isArray(t.relevantHashtags)).toBe(true);
    }
  });

  it('should auto-tag transfers', () => {
    const transfers = processed.filter(t => t.hasTransferTag);
    expect(transfers.length).toBeGreaterThan(0);

    // Each tagged transfer should have #transfer in memo
    for (const t of transfers) {
      expect(t.memo.toLowerCase()).toContain('#transfer');
    }
  });

  it('should auto-tag household expenses', () => {
    const household = processed.filter(t => t.hasHouseholdTag);
    expect(household.length).toBeGreaterThan(0);
  });

  it('should preserve original transaction data', () => {
    for (let i = 0; i < processed.length; i++) {
      expect(processed[i].id).toBe(sampleTransactions[i].id);
      expect(processed[i].date).toBe(sampleTransactions[i].date);
      expect(processed[i].amount).toBe(sampleTransactions[i].amount);
      expect(processed[i].source).toBe(sampleTransactions[i].source);
    }
  });
});

describe('trip processing on real data', () => {
  let withHashtags;
  let withTrips;

  beforeAll(() => {
    withHashtags = addHashtagsToTransactions(sampleTransactions);
    withTrips = processTransactionsWithTrips(withHashtags);
  });

  it('should assign trip names to some transactions', () => {
    const tripped = withTrips.filter(t => t.tripName);
    expect(tripped.length).toBeGreaterThan(0);
  });

  it('should not assign trips to transfer-tagged transactions', () => {
    const transfersWithTrips = withTrips.filter(t =>
      t.hasTransferTag && t.tripName && t.isAutoGeneratedTrip
    );
    expect(transfersWithTrips).toHaveLength(0);
  });

  it('should not assign trips to household-tagged transactions', () => {
    const householdWithTrips = withTrips.filter(t =>
      t.hasHouseholdTag && t.tripName && t.isAutoGeneratedTrip
    );
    expect(householdWithTrips).toHaveLength(0);
  });

  it('should generate valid trip summaries', () => {
    const summaries = getTripSummaries(withTrips);
    expect(summaries.length).toBeGreaterThan(0);

    for (const summary of summaries) {
      expect(summary.tripName).toBeTruthy();
      expect(summary.startDate).toMatch(/^\d{4}-\d{2}-\d{2}$/);
      expect(summary.endDate).toMatch(/^\d{4}-\d{2}-\d{2}$/);
      expect(summary.transactionCount).toBeGreaterThan(0);
      expect(summary.totalSpending).toBeLessThanOrEqual(0);
    }
  });

  it('should produce trip summaries with category breakdowns', () => {
    const summaries = getTripSummaries(withTrips);
    const withBreakdown = summaries.filter(s => s.categoryBreakdown?.length > 0);
    expect(withBreakdown.length).toBeGreaterThan(0);

    for (const summary of withBreakdown) {
      for (const [category, data] of summary.categoryBreakdown) {
        expect(typeof category).toBe('string');
        expect(data.amount).toBeGreaterThan(0);
        expect(data.count).toBeGreaterThan(0);
      }
    }
  });
});

describe('full processTransactions pipeline', () => {
  let fullyProcessed;

  beforeAll(() => {
    fullyProcessed = processTransactions(sampleTransactions);
  });

  it('should return all transactions with complete designation info', () => {
    expect(fullyProcessed.length).toBe(sampleTransactions.length);

    for (const t of fullyProcessed) {
      expect(t).toHaveProperty('hashtags');
      expect(t).toHaveProperty('hasTransferTag');
      expect(t).toHaveProperty('hasHouseholdTag');
      expect(t).toHaveProperty('tripName');
      expect(t).toHaveProperty('isAutoGeneratedTrip');
    }
  });

  it('should categorize every transaction into at least one designation or none', () => {
    const transfers = fullyProcessed.filter(t => t.hasTransferTag);
    const household = fullyProcessed.filter(t => t.hasHouseholdTag);
    const trips = fullyProcessed.filter(t => t.tripName);
    const undesignated = fullyProcessed.filter(t =>
      !t.hasTransferTag && !t.hasHouseholdTag && !t.tripName
    );

    // All transactions should be accounted for
    // (some may have multiple designations, some may have none)
    expect(transfers.length + household.length + trips.length + undesignated.length)
      .toBeGreaterThanOrEqual(fullyProcessed.length);
  });
});

describe('ownership end-to-end', () => {
  const ownership = {
    personNames: { left: { name: 'Peter' }, right: { name: 'Carey' } },
    categoryOwners: {},
  };

  it('a #peter memo makes a left-paid expense owned by left (no debt)', () => {
    const txns = [
      { id: 'a', date: '2024-03-01', source: 'left', amount: -50000, memo: 'thing #peter', category_id: null },
      { id: 'b', date: '2024-03-02', source: 'left', amount: -50000, memo: 'shared thing', category_id: null },
    ];
    const processed = addHashtagsToTransactions(txns, { ownership });
    expect(processed.find(t => t.id === 'a').ownerSide).toBe('left');

    const { net } = computeSettlement(processed, { leftName: 'Peter', rightName: 'Carey' });
    // Only the shared $50 counts: Carey owes Peter $25 (positive = right owes left).
    expect(net).toBe(25000);
  });

  it('all-shared net equals the legacy /2 formula on the fixture (scoped to shared)', () => {
    const processed = addHashtagsToTransactions(sampleTransactions, { ownership });
    // Scope to transactions the pipeline resolved as shared, so any stray #peter/#carey
    // memos or category mappings in the fixture can't skew the comparison.
    const shared = processed.filter(t => (t.ownerSide || 'shared') === 'shared');
    expect(shared.length).toBeGreaterThan(0);
    const legacy = shared.reduce((r, t) => r + (t.source === 'left' ? t.amount : -t.amount), 0) / 2;
    const { net } = computeSettlement(shared);
    expect(Math.abs(net)).toBe(Math.abs(legacy));
  });
});

describe('settlement watermark over the real fixture', () => {
  const processed = processTransactions(sampleTransactions, {
    ownership: { personNames: { left: { name: 'Left' }, right: { name: 'Right' } }, categoryOwners: {} },
  });

  it('marks 51 of 145 accruals settled (strict forward zero-crossing)', () => {
    const marked = markSettled(processed);
    const accruals = marked.filter(t => !t.hasTransferTag);
    expect(accruals.length).toBe(145);
    expect(accruals.filter(t => t.settled).length).toBe(51);
    expect(accruals.filter(t => !t.settled).length).toBe(94);
  });

  it('reports the authoritative net and total settled (no residual fields)', () => {
    const w = settlementWatermark(processed);
    expect(w.net).toBe(286155);
    expect(w.net).toBe(computeSettlement(processed).net); // authoritative headline
    expect(w.clearingPool).toBe(9067400);
    expect(w.openTailTotal).toBeUndefined();
    expect(w.residual).toBeUndefined();
  });
});

describe('funded groups over the real fixture', () => {
  const processed = processTransactions(sampleTransactions, {
    ownership: { personNames: { left: { name: 'Left' }, right: { name: 'Right' } }, categoryOwners: {} },
  });
  const summary = summarizeGroups(processed);

  it('produces 12 groups, 3 fully settled (balance only crossed zero once)', () => {
    expect(summary.groups.length).toBe(12);
    expect(summary.groups.filter(g => g.status === 'settled').length).toBe(3);
  });

  it('the settled groups are the earliest, up to the last time the balance was square', () => {
    const settled = summary.groups.filter(g => g.status === 'settled').map(g => g.key).sort();
    expect(settled).toEqual(['quarter:2024-Q2', 'quarter:2024-Q3', 'trip:trip2024Aug29-Sep3'].sort());
  });

  it('the group straddling the last zero-crossing is partial (2024-Q4: 7/9)', () => {
    const g = summary.groups.find(x => x.key === 'quarter:2024-Q4');
    expect(g.count).toBe(9);
    expect(g.settledCount).toBe(7);
    expect(g.status).toBe('partial');
  });

  it('a group entirely after the last square point is open (trip2025May9: 0/22)', () => {
    const g = summary.groups.find(x => x.key === 'trip:trip2025May9');
    expect(g.count).toBe(22);
    expect(g.settledCount).toBe(0);
    expect(g.status).toBe('open');
  });

  it('group nets sum to total accrued; the headline net is authoritative', () => {
    // total accrued = net + clearingPool = 286155 + 9067400 (group nets are unaffected by settled status)
    const totalAccrued = summary.groups.reduce((s, g) => s + g.net, 0);
    expect(totalAccrued).toBe(9353555);
    expect(summary.net).toBe(286155);
  });
});
