/**
 * Trip identification rule
 * Handles trip naming, exclusions, and trip assignment
 */

import { defaultConfig } from '../config.js';
import { extractAllHashtags, extractTripHashtags } from '../extractors/hashtags.js';
import { groupByConsecutiveDates, getDateRange } from '../extractors/tripGrouper.js';
import { isBillTransaction } from './householdRule.js';

/**
 * Generate a trip name from a date range
 * @param {DateTime} startDate - Trip start date
 * @param {DateTime} endDate - Trip end date
 * @returns {string} Generated trip name (e.g., "trip2024Jan15" or "trip2024Jan15-18")
 */
export function generateTripName(startDate, endDate) {
  const startMonth = startDate.toFormat('LLL'); // Jan, Feb, etc.
  const startDay = startDate.day;
  const startYear = startDate.year;

  // Same day or single date
  if (startDate.hasSame(endDate, 'day')) {
    return `trip${startYear}${startMonth}${startDay}`;
  }

  // Same month
  if (startDate.hasSame(endDate, 'month') && startDate.hasSame(endDate, 'year')) {
    return `trip${startYear}${startMonth}${startDay}`;
  }

  // Different month, same year
  if (startDate.hasSame(endDate, 'year')) {
    const endMonth = endDate.toFormat('LLL');
    const endDay = endDate.day;
    return `trip${startYear}${startMonth}${startDay}-${endMonth}${endDay}`;
  }

  // Different year
  const endYear = endDate.year;
  const endMonth = endDate.toFormat('LLL');
  const endDay = endDate.day;
  return `trip${startYear}${startMonth}${startDay}-${endYear}${endMonth}${endDay}`;
}

/**
 * Get the trip name for a group of transactions
 * Prioritizes manual hashtags over auto-generated names
 * @param {Array} transactions - Group of transactions
 * @param {string} timezone - Timezone for date calculations
 * @returns {Object} { tripName, isAutoGenerated }
 */
export function getTripNameForGroup(transactions, timezone = defaultConfig.timezone) {
  // Check for manual trip hashtag first
  for (const transaction of transactions) {
    const tripHashtags = extractTripHashtags(transaction);
    if (tripHashtags.length > 0) {
      return {
        tripName: tripHashtags[0],
        isAutoGenerated: false,
      };
    }
  }

  // Generate name from date range
  const { startDate, endDate } = getDateRange(transactions, timezone);
  if (!startDate || !endDate) {
    return { tripName: null, isAutoGenerated: false };
  }

  return {
    tripName: generateTripName(startDate, endDate),
    isAutoGenerated: true,
  };
}

/**
 * Check if a transaction should be included in trip processing
 * @param {Object} transaction - Transaction to check
 * @param {Object} config - Configuration object
 * @returns {boolean} True if transaction should be processed for trips
 */
export function shouldIncludeInTripProcessing(transaction, config = defaultConfig) {
  const { excludeHousehold, excludeTransfers, excludePositive } = config.trip;

  // Exclude household/bill transactions if configured
  if (excludeHousehold && isBillTransaction(transaction, config)) {
    return false;
  }

  // Exclude transactions with #household tag
  if (excludeHousehold) {
    const hashtags = extractAllHashtags(transaction);
    if (hashtags.some(tag => tag.toLowerCase() === 'household')) {
      return false;
    }
  }

  // Exclude transactions with #transfer tag
  if (excludeTransfers) {
    const hashtags = extractAllHashtags(transaction);
    if (hashtags.some(tag => tag.toLowerCase() === 'transfer')) {
      return false;
    }
  }

  // Exclude positive transactions (income) if configured
  if (excludePositive && transaction.amount > 0) {
    return false;
  }

  return true;
}

/**
 * Process transactions and assign trip information
 * @param {Array} transactions - All transactions
 * @param {Object} config - Configuration object
 * @returns {Array} Transactions with trip information added
 */
export function processTrips(transactions, config = defaultConfig) {
  if (!transactions || transactions.length === 0) {
    return [];
  }

  // Filter transactions for trip processing
  const tripEligible = transactions.filter(t => shouldIncludeInTripProcessing(t, config));

  // Group by consecutive dates
  const tripGroups = groupByConsecutiveDates(tripEligible, config);

  // Build a map of transaction ID to trip info
  const tripAssignments = new Map();

  for (const group of tripGroups) {
    const { tripName, isAutoGenerated } = getTripNameForGroup(group, config.timezone);

    for (const transaction of group) {
      tripAssignments.set(transaction.id, {
        tripName,
        isAutoGeneratedTrip: isAutoGenerated,
        tripHashtags: extractTripHashtags(transaction),
      });
    }
  }

  // Return all transactions with trip info added
  return transactions.map(t => {
    const tripInfo = tripAssignments.get(t.id);
    return {
      ...t,
      tripName: tripInfo?.tripName || null,
      isAutoGeneratedTrip: tripInfo?.isAutoGeneratedTrip || false,
      tripHashtags: tripInfo?.tripHashtags || extractTripHashtags(t),
    };
  });
}

/**
 * Get trip summaries from processed transactions
 * @param {Array} transactions - Transactions with trip info
 * @returns {Array} Array of trip summary objects
 */
export function getTripSummaries(transactions) {
  // Group transactions by trip name
  const tripMap = new Map();

  for (const t of transactions) {
    if (!t.tripName) continue;

    if (!tripMap.has(t.tripName)) {
      tripMap.set(t.tripName, []);
    }
    tripMap.get(t.tripName).push(t);
  }

  // Build summaries
  const summaries = [];

  for (const [tripName, tripTransactions] of tripMap) {
    const { startDate, endDate } = getDateRange(tripTransactions);

    // Calculate total spending (only negative amounts)
    const totalSpending = tripTransactions.reduce(
      (sum, t) => sum + (t.amount < 0 ? t.amount : 0),
      0
    );

    // Get frequent words from payee and memo
    const frequentWords = getMostFrequentWords(tripTransactions, 3);

    // Calculate category breakdown
    const categoryBreakdown = getCategoryBreakdown(tripTransactions);

    summaries.push({
      tripName,
      startDate: startDate?.toISODate(),
      endDate: endDate?.toISODate(),
      transactionCount: tripTransactions.length,
      totalSpending,
      frequentWords,
      categoryBreakdown,
      isAutoGenerated: tripTransactions[0]?.isAutoGeneratedTrip || false,
    });
  }

  return summaries;
}

/**
 * Get spending breakdown by category for a set of transactions
 * @param {Array} transactions - Array of transactions
 * @returns {Array} Array of [categoryName, { amount, count }] sorted by amount desc
 */
function getCategoryBreakdown(transactions) {
  const categories = {};

  for (const t of transactions) {
    // Only count expenses (negative amounts)
    if (t.amount >= 0) continue;

    const cat = t.category_name || 'Uncategorized';
    if (!categories[cat]) {
      categories[cat] = { amount: 0, count: 0 };
    }
    categories[cat].amount += Math.abs(t.amount);
    categories[cat].count++;
  }

  // Convert to array and sort by amount (highest first)
  return Object.entries(categories)
    .sort((a, b) => b[1].amount - a[1].amount);
}

/**
 * Get most frequent words from transaction payee and memo fields
 * @param {Array} transactions - Array of transactions
 * @param {number} count - Number of words to return
 * @returns {Array} Most frequent words
 */
function getMostFrequentWords(transactions, count = 3) {
  const stopWords = new Set([
    'the', 'and', 'or', 'but', 'in', 'on', 'at', 'to', 'for', 'of', 'a', 'an',
    'is', 'it', 'by', 'with', 'as', 'from', 'this', 'that', 'was', 'are', 'be',
  ]);

  const wordCounts = new Map();

  for (const t of transactions) {
    const text = `${t.payee_name || ''} ${t.memo || ''}`.toLowerCase();
    const words = text.match(/[a-zA-Z]{4,}/g) || [];

    for (const word of words) {
      if (stopWords.has(word)) continue;
      if (word.startsWith('trip') || word.startsWith('household') || word.startsWith('transfer')) continue;

      wordCounts.set(word, (wordCounts.get(word) || 0) + 1);
    }
  }

  // Sort by frequency and return top N
  return [...wordCounts.entries()]
    .sort((a, b) => b[1] - a[1])
    .slice(0, count)
    .map(([word]) => word);
}
